name: CheckStyle

on: 
  pull_request:
    branches: [ "main" ]

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: CheckStyle Job
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: 'github-pr-check'
