name: FirstInteraction

on: 
  pull_request:
    branches: [ "main" ]

jobs:
  first_interaction:
      runs-on: ubuntu-latest
      name: First Interaction
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: First interaction
          uses: actions/first-interaction@v1.3.0
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            issue-message: "Thank you for reporting your first issue, we hope it is not the last."
            pr-message: "Thank you for making your first pull request, we hope it's not your last."
